#
# Generate devices configs
# This playbook was created using Ansible 2.9.6
---
- name: Apply interface configurations to Cisco IOS and NXOS managed devices
  hosts: ios,nxos
  vars:
    includes_dir: ../../includes
    diff_dir: cfg-diffs
    cfg_dir: ../../lab-3-create-service-data-model/generated-cfgs/infrastructure/
  
  tasks:
  - include_tasks: "{{ includes_dir }}/create-folder-structure.yml"
    vars:
      dir_name: "{{ diff_dir }}"
      create_subfolders: False
    run_once: true

  - name: Configure Cisco IOS device
    ios_config:
      src: "{{ cfg_dir }}/{{ inventory_hostname }}/10-interfaces.cfg"
      defaults: yes
    register: ios_config_diff
    check_mode: "{{ not commit_changes | default(false) }}"
    when: ansible_network_os == 'ios'

  - name: Register ios_config_diff variable
    set_fact:
      config_changed: "{{ ios_config_diff }}"
    when: ansible_network_os == 'ios'

  - name: Configure Cisco NXOS device
    nxos_config:
      src: "{{ cfg_dir }}/{{ inventory_hostname }}/10-interfaces.cfg"
      defaults: yes
    register: nxos_config_diff
    check_mode: "{{ not commit_changes | default(false) }}"
    when: ansible_network_os == 'nxos'

  - name: Register nxos_config_diff variable
    set_fact:
      config_changed: "{{ nxos_config_diff }}"
    when: ansible_network_os == 'nxos'

  - template: src=../j2-templates/10-interfaces-config-diff.j2 dest={{ diff_dir }}/{{inventory_hostname}}-10-interfaces.diff
    when: hostvars[inventory_hostname]['config_changed']['changed'] == true
    check_mode: false
    changed_when: false

- name: Apply interface configurations to Mikrotik managed devices
  hosts: routeros
  vars:
    cfg_dir: ../../lab-3-create-service-data-model/generated-cfgs/infrastructure

  tasks:
  - name: Deploy infrastructure config to Mikrotik devices
    routeros_command:
      commands: "{{ item }}"
    with_lines: cat {{ cfg_dir }}/{{ inventory_hostname }}/10-interfaces.cfg