#
# Generate devices configs
# This playbook was created using Ansible 2.9.6
---
- name: Apply configurations to Cisco IOS managed devices
  hosts: ios
  vars:
    includes_dir: ../includes
    diff_dir: cfg-diffs

  tasks:
  - include_vars: ../lab-3-create-service-data-model/data-models/nodes.yml

  - include_tasks: "{{ includes_dir }}/create-folder-structure.yml"
    vars:
      dir_name: "{{ diff_dir }}"
      create_subfolders: False
    run_once: true

  - name: Configure Cisco IOS devices using NAPALM
    napalm_install_config:
      hostname={{ ansible_host }}
      username={{ ansible_user }}
      dev_os={{ ansible_network_os }}
      password={{ ansible_ssh_pass }}
      config_file={{ item.config_location_dir }}/{{ inventory_hostname }}/{{ item.config_part }}.cfg
      commit_changes={{ not ansible_check_mode }}
      replace_config=False
      get_diffs=True
      diff_file={{ diff_dir }}/{{ inventory_hostname }}-{{ item.config_part }}.diff

    with_items:
      - { config_part: 01-base, config_location_dir: ../lab-3-create-service-data-model/generated-cfgs/infrastructure }
      - { config_part: 10-interfaces, config_location_dir: ../lab-3-create-service-data-model/generated-cfgs/infrastructure }
      - { config_part: 20-routing, config_location_dir: ../lab-3-create-service-data-model/generated-cfgs/infrastructure }
      - { config_part: svi-service, config_location_dir: ../lab-3-create-service-data-model/generated-cfgs/svi-service }

- name: Apply configurations to Cisco Nexus devices
  hosts: nxos

  tasks:

  - name: Create temp folder for running configs
    file: path=temp-configs state=directory
    changed_when: false

  - name: Execute show run on device
    nxos_command: commands="show running"
    register: running

  - name: Saving running configs to temp folder
    copy:
      content: "{{ running.stdout[0] }}"
      dest: "temp-configs/{{inventory_hostname}}.cfg"
    changed_when: false

  - name: Configure Nexus devices
    nxos_config:
      src: "{{ item.config_location_dir }}/{{ inventory_hostname }}/{{ item.config_part }}.cfg"
      running_config: "temp-configs/{{inventory_hostname}}.cfg"

    with_items:
      - { config_part: 01-base, config_location_dir: ../lab-3-create-service-data-model/generated-cfgs/infrastructure }
      - { config_part: 10-interfaces, config_location_dir: ../lab-3-create-service-data-model/generated-cfgs/infrastructure }
      - { config_part: 20-routing, config_location_dir: ../lab-3-create-service-data-model/generated-cfgs/infrastructure }
      - { config_part: svi-service, config_location_dir: ../lab-3-create-service-data-model/generated-cfgs/svi-service } 

  - name: Clean temp directory
    file: path=temp-configs state=absent
    run_once: true
    changed_when: false

- name: Apply configurations to Mikrotik devices
  hosts: ros

  tasks:

  - name: Deploy infrastructure config to Mikrotik devices
    routeros_command:
      commands: "{{ item }}"

    with_lines: cat ../lab-3-create-service-data-model/generated-cfgs/infrastructure/{{ inventory_hostname }}.cfg

  - name: Deploy service config to Mikrotik devices
    routeros_command:
      commands: "{{ item }}"

    with_lines: cat ../lab-3-create-service-data-model/generated-cfgs/svi-service/{{ inventory_hostname }}/svi-service.cfg
