#
# Generate devices configs
# This playbook was created using Ansible 2.9.6
---
- name: Verify SVI service configurations for all devices
  hosts: svi_service
  vars:
    napalm_validation_dir: ../../lab-3-create-service-data-model/napalm-validation

  tasks:
  - name: Get validation report to interface configuration
    napalm_validate:
      hostname={{ ansible_host }}
      username={{ ansible_user }}
      dev_os={{ napalm_dev_os }}
      password={{ ansible_ssh_pass }}
      validation_file={{ napalm_validation_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}-validate-svi-service.yml
    register: svi_report

  - debug:
      var: svi_report.compliance_report