#
# Generate svi service configs
# This playbook was created using Ansible 2.7.14
---
- name: Generate svi service configurations
  hosts: all
  vars:
    cfg_dir: generated-cfgs/svi-service
    includes_dir: ../includes

  tasks:
  - include_vars: data-models/svi-service.yml

  - import_tasks: "{{ includes_dir }}/create-folder-structure.yml"
    vars:
      dir_name: "{{ cfg_dir }}"
      create_subfolders: true
    run_once: true

  - name: Generate svi service configuration
    template: src=j2-templates/{{ ansible_network_os }}/svi-service.j2 dest={{ cfg_dir }}/{{ inventory_hostname }}/svi-service.cfg
    changed_when: false