#
# Generate devices configs
# This playbook was created using Ansible 2.7.14
---
- name: Generate configurations
  hosts: all
  vars:
    output_cfg_dir: generated-cfgs 

  tasks:
  - include_vars: data-models/nodes.yml

  - name: "Clear configs directory"
    local_action: file path={{ output_cfg_dir }}/infrastructure state=absent
    changed_when: false
    run_once: true

  - name: "Generate infrastructure configs folder structure"
    local_action: file path={{ output_cfg_dir }}/infrastructure/{{ inventory_hostname }} state=directory
    changed_when: false

  - name: Generate base configuration for Cisco IOS devices
    template: src=j2-templates/cisco-ios/01-base.j2 dest={{ output_cfg_dir }}/infrastructure/{{inventory_hostname}}/01-base.cfg
    when: ansible_network_os == 'ios'
    changed_when: false

  - name: Generate base configuration for Cisco NXOS devices
    template: src=j2-templates/cisco-nxos/01-base.j2 dest={{ output_cfg_dir }}/infrastructure/{{inventory_hostname}}/01-base.cfg
    when: ansible_network_os == 'nxos'
    changed_when: false   

  - name: Generate base configuration for Mikrotik devices
    template: src=j2-templates/mikrotik-ros/01-base.j2 dest={{ output_cfg_dir }}/infrastructure/{{inventory_hostname}}/01-base.cfg
    when: ansible_network_os == 'ros'
    changed_when: false

  - name: Generate interface configuration for Cisco IOS devices
    template: src=j2-templates/cisco-ios/10-interfaces.j2 dest={{ output_cfg_dir }}/infrastructure/{{inventory_hostname}}/10-interfaces.cfg
    when: ansible_network_os == 'ios'
    changed_when: false

  - name: Generate interface configuration for Cisco NXOS devices
    template: src=j2-templates/cisco-nxos/10-interfaces.j2 dest={{ output_cfg_dir }}/infrastructure/{{inventory_hostname}}/10-interfaces.cfg
    when: ansible_network_os == 'nxos'
    changed_when: false

  - name: Generate routing configuration for Cisco IOS devices
    template: src=j2-templates/cisco-ios/20-routing.j2 dest={{ output_cfg_dir }}/infrastructure/{{inventory_hostname}}/20-routing.cfg
    when: ansible_network_os == 'ios'    
    changed_when: false

  - name: Generate routing configuration for Cisco NXOS devices
    template: src=j2-templates/cisco-nxos/20-routing.j2 dest={{ output_cfg_dir }}/infrastructure/{{inventory_hostname}}/20-routing.cfg
    when: ansible_network_os == 'nxos'    
    changed_when: false

  - name: Generate interface configuration for Mikrotik devices
    template: src=j2-templates/mikrotik-ros/10-interfaces.j2 dest={{ output_cfg_dir }}/infrastructure/{{inventory_hostname}}/10-interfaces.cfg
    when: ansible_network_os == 'ros'
    changed_when: false

  - name: Generate routing configuration for Mikrotik devices
    template: src=j2-templates/mikrotik-ros/20-routing.j2 dest={{ output_cfg_dir }}/infrastructure/{{inventory_hostname}}/20-routing.cfg
    when: ansible_network_os == 'ros'
    changed_when: false

  - name: Assemble configurations
    assemble: src={{ output_cfg_dir }}/infrastructure/{{ inventory_hostname }} dest={{ output_cfg_dir }}/infrastructure/{{ inventory_hostname }}.cfg
    changed_when: false
