#
# Generate devices configs
# This playbook was created using Ansible 2.7.14
---
- name: Generate configurations
  hosts: all
  vars:
    cfg_dir: generated-cfgs/infrastructure
    includes_dir: ../includes

  tasks:
  - include_vars: data-models/nodes.yml

  - include_tasks: "{{ includes_dir }}/create-folder-structure.yml"
    vars:
      dir_name: "{{ cfg_dir }}"
      create_subfolders: true
    run_once: true

  - name: Generate base configuration for devices
    template: src=j2-templates/{{ ansible_network_os }}/01-base.j2 dest={{ cfg_dir }}/{{inventory_hostname}}/01-base.cfg
    changed_when: false

  - name: Generate interface configuration for devices
    template: src=j2-templates/{{ ansible_network_os }}/10-interfaces.j2 dest={{ cfg_dir }}/{{inventory_hostname}}/10-interfaces.cfg
    changed_when: false

  - name: Generate routing configuration for devices
    template: src=j2-templates/{{ ansible_network_os }}/20-routing.j2 dest={{ cfg_dir }}/{{inventory_hostname}}/20-routing.cfg    
    changed_when: false

  - name: Assemble configurations
    assemble: src={{ cfg_dir }}/{{ inventory_hostname }} dest={{ cfg_dir }}/{{ inventory_hostname }}.cfg
    changed_when: false