#
# Generate nodes data model using infrastructure data model
# This playbook was created using Ansible 2.7.14
---
- hosts: localhost
  
  tasks:
  - include_vars: "data-models/infrastructure.yml"

  - name: Create hosts file from infrastructure data model
    template: src=j2-templates/infrastructure-to-hosts.j2 dest=data-models/hosts

  - name: Create per-node data model from infrastructure data model
    template: src=j2-templates/infrastructure-to-nodes.j2 dest=data-models/nodes-infrastructure.yml
